name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main  # Change to your main branch if it's named differently

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Sync Project Files to Droplet
        run: |
          rsync -avz --delete ./ your_user@${{ secrets.DO_SERVER_IP }}:/var/www/html/Ecommerce/
        env:
          RSYNC_RSH: "ssh -o StrictHostKeyChecking=no"

      - name: Restart Apache
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_SSH_USER }}@${{ secrets.DO_SERVER_IP }} << 'EOF'
            sudo systemctl reload apache2
          EOF
